# Generated by Django 5.2.7 on 2025-10-25 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('semestre', models.CharField(max_length=20)),
                ('promedio', models.FloatField()),
                ('trabajo', models.CharField(max_length=50)),
                ('reprobado', models.BooleanField(default=False)),
                ('riesgo', models.CharField(blank=True, max_length=20, null=True)),
                ('probabilidad', models.FloatField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveSmallIntegerField()),
                ('semestre', models.CharField(blank=True, max_length=20, null=True)),
                ('promedio', models.FloatField()),
                ('trabajo', models.CharField(blank=True, max_length=10, null=True)),
                ('reprobado', models.CharField(blank=True, max_length=10, null=True)),
                ('riesgo', models.CharField(max_length=10)),
                ('probabilidad', models.FloatField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='appprincipal.student')),
            ],
        ),
    ]
