# Generated by Django 5.2.7 on 2025-10-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('promedio', models.FloatField()),
                ('trabajo', models.BooleanField()),
                ('reprobado', models.BooleanField()),
                ('riesgo', models.CharField(max_length=10)),
                ('probabilidad', models.FloatField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
