# Generated by Django 5.2.7 on 2025-10-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprincipal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='probabilidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='promedio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='reprobado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='riesgo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='trabajo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
